[mypy]
python_version = 3.12
strict = True
exclude = (venv|\.git|\.venv)

[mypy-streamlit.*]
disable_error_code = attr-defined

[mypy-sklearn.*]
ignore_missing_imports = True
follow_untyped_imports = False

